import type { BankQ } from "./bank";

const q = (
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  difficulty = 2,
  timeLimit = 40,
): BankQ => ({
  category: "grammar",
  difficulty,
  prompt,
  options,
  correctIndex,
  explanation,
  timeLimit,
});

export const GRAMMAR: BankQ[] = [
  q(
    "By the time the interview panel arrived, we ___ the product demo.",
    ["had completed", "completed", "were completing", "complete"],
    0,
    "An action finished before another past action takes the past perfect: had completed.",
    2,
  ),
  q(
    "Neither of the two candidates ___ convincing enough for the final round.",
    ["were", "was", "have been", "are"],
    1,
    "Neither is singular, so the verb takes the singular form: was.",
    1,
  ),
  q(
    "She was appointed ___ head of the customer success team.",
    ["a", "an", "the", "no article"],
    2,
    "Unique, one-of-a-kind titles take the definite article: the head of…",
    1,
  ),
  q(
    "The director is keen ___ expanding the R&D wing.",
    ["in", "on", "at", "with"],
    1,
    "The fixed collocation is keen on (doing something).",
    1,
  ),
  q(
    "Before she joined us, Priya ___ at a fintech for four years.",
    ["worked", "has worked", "had worked", "is working"],
    2,
    "Four years of work finished before the past joining → past perfect.",
    2,
  ),
  q(
    "The engineer ___ led the migration is part of the interview loop.",
    ["which", "who", "whom", "whose"],
    1,
    "A relative pronoun referring to a person as the subject is who.",
    2,
  ),
  q(
    "If I ___ the client call properly, I would have sent an apology note.",
    ["handled", "had handled", "would handle", "handle"],
    1,
    "Third conditional for an unreal past: if + past perfect, would have + past participle.",
    3,
  ),
  q(
    "Choose the correct plural of “criterion”.",
    ["criterions", "criteria", "criteriae", "criteria's"],
    1,
    "Criterion (singular) → criteria (plural), from Latin.",
    1,
  ),
  q(
    "Which sentence is punctuated correctly?",
    [
      "The recruiter said, “we are hiring”",
      "The recruiter said, “We are hiring.”",
      "The recruiter said,“We are hiring.”",
      "The recruiter said, “We are Hiring”",
    ],
    1,
    "The quoted sentence needs a capital start, a space after the comma, and its full stop inside the quotes.",
    2,
  ),
  q(
    "The launch report ___ by the team before Friday.",
    ["will submit", "will be submitted", "is submitting", "submits"],
    1,
    "The report cannot submit itself — passive voice is needed: will be submitted.",
    1,
  ),
  q(
    "Each of the team members ___ agreed to the revised terms.",
    ["have", "has", "are", "were"],
    1,
    "Each is singular even after “of the members”, so it takes has.",
    2,
  ),
  q(
    "You ___ finish the background verification by Monday.",
    ["can", "must", "might", "should to"],
    1,
    "Obligation uses must; “should to” is never grammatical.",
    1,
  ),
  q(
    "Find the error: “One of my colleague is joining next month.”",
    ["One of", "my colleague", "is joining", "No error"],
    1,
    "One of + plural noun → one of my colleagues.",
    1,
  ),
  q(
    "This quarter's numbers ___ clearly from last quarter's.",
    ["differ", "differs", "differing", "are differing"],
    0,
    "Numbers is plural → the verb takes differ without -s.",
    1,
  ),
  q(
    "He worked late every night, ___ he still missed the deadline.",
    ["so", "but also", "yet", "and that"],
    2,
    "Yet signals the contrast between hard work and the missed deadline.",
    2,
  ),
  q(
    "Scarcely had the meeting begun ___ the power went off.",
    ["when", "than", "since", "until"],
    0,
    "Scarcely / hardly … when is the fixed inversion pattern.",
    3,
  ),
  q(
    "The founders ___ vision impressed the investors deeply.",
    ["founders", "founders'", "founders''s", "the founders's"],
    1,
    "Plural noun ending in -s takes only an apostrophe: founders' vision.",
    2,
  ),
  q(
    "Neither the VP nor the two managers ___ present at the review.",
    ["was", "were", "is", "has been"],
    1,
    "With neither…nor the verb agrees with the closer subject: the two managers were.",
    3,
  ),
  q(
    "I look forward ___ from you soon.",
    ["hearing", "to hear", "to hearing", "heard"],
    2,
    "Look forward to is always followed by a gerund: to hearing.",
    1,
  ),
  q(
    "By 2030, the group ___ a fully automated warehouse.",
    ["will establish", "will have established", "established", "is establishing"],
    1,
    "Future perfect for something completed by a future deadline.",
    2,
  ),
  q(
    "The proposal, along with its annexures, ___ approved yesterday.",
    ["were", "was", "have been", "are"],
    1,
    "Phrases like along with do not change the subject — proposal (singular) was approved.",
    3,
  ),
  q(
    "Hardly ___ left the office when it started to rain.",
    ["I had", "had I", "I did", "did I"],
    1,
    "Negative adverb at the start triggers inversion: hardly had I left.",
    3,
  ),
  q(
    "We need a more ___ way of estimating release risk.",
    ["systematic", "systemically", "systemics", "systemized"],
    0,
    "An adjective is needed before “way”: systematic.",
    2,
  ),
  q(
    "Of all the candidates we interviewed, this one is the ___ fit for the role.",
    ["good", "better", "best", "bestest"],
    2,
    "Comparing three or more uses the superlative: best.",
    1,
  ),
  q(
    "Find the error: “He doesn't knows anything about SQL.”",
    ["He", "doesn't knows", "anything about", "No error"],
    1,
    "After doesn't the base verb is required: doesn't know.",
    1,
  ),
  q(
    "The candidate did extremely well, ___?",
    ["does he", "didn't he", "did he", "wasn't he"],
    1,
    "A positive past-tense statement takes a negative tag in the same tense: didn't he.",
    2,
  ),
];
