import type { BankQ } from "./bank";

const q = (
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  difficulty = 2,
  timeLimit = 45,
): BankQ => ({
  category: "logical",
  difficulty,
  prompt,
  options,
  correctIndex,
  explanation,
  timeLimit,
});

export const LOGICAL: BankQ[] = [
  q(
    "Find the next number: 2, 6, 12, 20, 30, ?",
    ["36", "40", "42", "44"],
    2,
    "Differences grow by 2: +4, +6, +8, +10, so next is +12 → 42.",
    1,
  ),
  q(
    "Find the next number: 3, 9, 27, 81, ?",
    ["162", "243", "324", "108"],
    1,
    "Each term is tripled: 81 × 3 = 243.",
    1,
  ),
  q(
    "Find the next number: 5, 10, 17, 26, 37, ?",
    ["46", "49", "50", "51"],
    2,
    "Pattern n² + 4: 7² + 4 = 53? No — differences are +5, +7, +9, +11, so +13 → 50.",
    2,
  ),
  q(
    "Find the next number: 1, 1, 2, 3, 5, 8, ?",
    ["10", "11", "13", "15"],
    2,
    "Fibonacci: each term is the sum of the previous two → 5 + 8 = 13.",
    1,
  ),
  q(
    "Find the next number: 100, 95, 85, 70, 50, ?",
    ["30", "25", "20", "15"],
    1,
    "Subtractions grow by 5: −5, −10, −15, −20, −25 → 25.",
    2,
  ),
  q(
    "If CODE is written as DFPE, how is DATA written?",
    ["EBUB", "EBUC", "DCVB", "FAGB"],
    0,
    "Each letter shifts +1: D→E, A→B, T→U, A→B → EBUB.",
    1,
  ),
  q(
    "If SKILL is written as TLJMM, how is TALE written?",
    ["UBMF", "VBMF", "TALE", "UBMG"],
    0,
    "Each letter shifts +1: T→U, A→B, L→M, E→F → UBMF.",
    1,
  ),
  q(
    "If A = 1, B = 2 … Z = 26, what is the sum of the letters in RAIN?",
    ["38", "40", "42", "44"],
    2,
    "R(18) + A(1) + I(9) + N(14) = 42.",
    2,
  ),
  q(
    "If BAKERY is coded as KCZDST, how is CAKE coded?",
    ["LBTN", "KASM", "LBSM", "MCTU"],
    0,
    "Each letter shifts +9 (wrapping around): C→L, A→J, K→T, E→N → LBTN.",
    3,
  ),
  q(
    "Statements: All engineers are logical. Some logical people are managers. Which conclusion follows?",
    [
      "Some managers may be engineers",
      "All managers are engineers",
      "No manager is an engineer",
      "Some engineers are not logical",
    ],
    0,
    "The overlap between “logical” groups is not fixed, so only the possibility conclusion holds.",
    3,
  ),
  q(
    "Statements: No cat is a dog. All dogs are animals. Which conclusion follows?",
    [
      "Some animals are dogs",
      "No cat is an animal",
      "All cats are animals",
      "No dog is an animal",
    ],
    0,
    "If all dogs are animals, some animals are dogs. The cat-animal relation is not established.",
    2,
  ),
  q(
    "Pointing to a photo, Ravi says, “She is the daughter of my grandfather's only son.” Who is she to Ravi?",
    ["sister", "aunt", "cousin", "mother"],
    0,
    "Grandfather's only son is Ravi's father; his daughter is Ravi's sister.",
    2,
  ),
  q(
    "A is B's father and B is C's mother. How is A related to C?",
    ["grandfather", "uncle", "father-in-law", "brother"],
    0,
    "A is the father of C's mother, so A is C's grandfather.",
    1,
  ),
  q(
    "Walk 5 m north, turn right and walk 3 m, turn right and walk 4 m. You are from the start point towards:",
    ["north", "north-east", "east", "south-east"],
    1,
    "Net movement is 1 m north and 3 m east → north-east of the start.",
    2,
  ),
  q(
    "Walk 10 m east, then 5 m north. How far are you from the start?",
    ["11.18 m", "15 m", "7.07 m", "5 m"],
    0,
    "Pythagoras: √(10² + 5²) = √125 ≈ 11.18 m.",
    2,
  ),
  q(
    "Arun ranks 10th from the top and 20th from the bottom in his class. How many students are there?",
    ["29", "30", "31", "32"],
    0,
    "Total = 10 + 20 − 1 = 29 (Arun counted twice).",
    1,
  ),
  q(
    "Find the odd one out.",
    ["Apple", "Mango", "Carrot", "Banana"],
    2,
    "Carrot is a vegetable; the others are fruits.",
    1,
  ),
  q(
    "If Monday is called Sunday, Tuesday is called Monday, and so on, what is Wednesday called?",
    ["Sunday", "Monday", "Tuesday", "Thursday"],
    2,
    "Every weekday gets the name of the day before it: Wednesday → Tuesday.",
    2,
  ),
  q(
    "What is the angle between the two hands of a clock at exactly 3:00?",
    ["60°", "90°", "105°", "120°"],
    1,
    "The hour hand is at 90° and the minute hand at 0° → 90° apart.",
    1,
  ),
  q(
    "3 machines make 3 widgets in 3 minutes. How long do 100 machines take to make 100 widgets?",
    ["3 minutes", "100 minutes", "300 minutes", "1 minute"],
    0,
    "Each machine makes 1 widget in 3 minutes, so 100 machines make 100 in the same 3 minutes.",
    3,
  ),
  q(
    "Find the next number: 8, 5, 7, 4, 6, 3, 5, ?",
    ["3", "2", "4", "1"],
    1,
    "Two interleaved series: 8,7,6,5,? → 4? No — positions 1,3,5,7 fall by 1 (8,7,6,5) and 2,4,6,8 fall by 1 (5,4,3,2) → 2.",
    2,
  ),
  q(
    "Statements: All offers require approval. This deal is an offer. Which conclusion follows?",
    [
      "This deal requires approval",
      "This deal is already approved",
      "Approval is unnecessary for deals",
      "This deal is not an offer",
    ],
    0,
    "Direct application: since all offers require approval and this is an offer, it requires approval.",
    1,
  ),
  q(
    "What is WINTER written as in a mirror image?",
    ["RETNIW", "RETWIN", "TWIRNE", "RETNWI"],
    0,
    "A mirror reverses order and each letter: WINTER → RETNIW.",
    2,
  ),
  q(
    "Two teammates share 48 tasks in the ratio 5 : 3. How many does the first teammate get?",
    ["24", "28", "30", "32"],
    2,
    "5/(5+3) × 48 = 30 tasks.",
    1,
  ),
];
