import type { BankQ } from "./bank";

const q = (
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  difficulty = 2,
  timeLimit = 40,
): BankQ => ({
  category: "verbal",
  difficulty,
  prompt,
  options,
  correctIndex,
  explanation,
  timeLimit,
});

export const VERBAL: BankQ[] = [
  q(
    "Choose the closest synonym of CANDID: “She gave a ___ answer to a hard question.”",
    ["frank", "reserved", "hostile", "vague"],
    0,
    "Candid means open, honest and direct — closest to frank.",
    1,
  ),
  q(
    "Choose the antonym of ABUNDANT: “Funds were scarce, not ___.”",
    ["scarce", "ample", "rich", "plentiful"],
    0,
    "Abundant means more than enough; scarce is its opposite.",
    1,
  ),
  q(
    "The idiom “to throw in the towel” means:",
    ["to give up", "to celebrate", "to take a break", "to negotiate"],
    0,
    "Borrowed from boxing — throwing the towel in ends the fight, i.e. you quit.",
    1,
  ),
  q(
    "Choose the closest synonym of DILIGENT.",
    ["sloppy", "assiduous", "restless", "careless"],
    1,
    "Diligent and assiduous both mean careful, persistent and hardworking.",
    2,
  ),
  q(
    "Choose the antonym of LAUD.",
    ["praise", "commend", "disparage", "eulogize"],
    2,
    "Laud means to praise highly; disparage means to speak of it unworthily.",
    2,
  ),
  q(
    "A person who can speak many languages is a ___.",
    ["bilingual", "polyglot", "interpreter", "dictionarian"],
    1,
    "Bilingual = two languages; polyglot = many languages.",
    1,
  ),
  q(
    "“To cut corners” means:",
    [
      "to do something with less effort or expense",
      "to take a shortcut on the road",
      "to reduce the team size",
      "to finish a meeting early",
    ],
    0,
    "It means taking shortcuts that reduce quality or safety.",
    2,
  ),
  q(
    "Choose the closest synonym of PRAGMATIC.",
    ["idealistic", "practical", "theoretical", "dreamy"],
    1,
    "A pragmatic person deals with things sensibly and realistically.",
    1,
  ),
  q(
    "Choose the antonym of ELOQUENT.",
    ["fluent", "persuasive", "inarticulate", "expressive"],
    2,
    "Eloquent = fluent and persuasive in speech; inarticulate is the opposite.",
    2,
  ),
  q(
    "Complete the idiom: “All that preparation went ___; the interview got cancelled.”",
    ["to waste", "on time", "in hand", "under way"],
    0,
    "To go to waste means to be wasted or not make use of something.",
    1,
  ),
  q(
    "Choose the closest synonym of MITIGATE.",
    ["worsen", "lessen", "delay", "verify"],
    1,
    "To mitigate a risk is to make it less severe — to lessen it.",
    2,
  ),
  q(
    "Pick the word that best fits: “The analyst's ___ reading of the market data guided the strategy.”",
    ["insightful", "narrow", "casual", "vague"],
    0,
    "A strategy would be guided by a sharp, meaningful reading — insightful.",
    2,
  ),
  q(
    "Choose the antonym of RETREAT.",
    ["withdraw", "retire", "advance", "flee"],
    2,
    "Retreat means to move back; advance means to move forward.",
    1,
  ),
  q(
    "“In the long run” means:",
    ["eventually, over a period of time", "in a hurry", "in secret", "with great difficulty"],
    0,
    "It refers to the eventual outcome, not the short term.",
    1,
  ),
  q(
    "Choose the closest synonym of TENDENTIOUS.",
    ["fair", "balanced", "biased", "factual"],
    2,
    "Tendentious means revealing a hidden bias toward a conclusion.",
    3,
  ),
  q(
    "One word for “to say or do again”: the manager ___ the launch date.",
    ["reiterated", "resigned", "recused", "retracted"],
    0,
    "Reiterate = repeat. Retract (withdraw) is the trap option.",
    1,
  ),
  q(
    "Despite the setback, she stayed ___ and kept pushing the release.",
    ["fragile", "resilient", "fragrant", "frivolous"],
    1,
    "Resilient describes someone who recovers quickly from difficulty.",
    1,
  ),
  q(
    "Choose the antonym of OBSCURE.",
    ["vague", "ambiguous", "clear", "dim"],
    2,
    "Obscure means unclear or hidden; clear is the direct opposite.",
    1,
  ),
  q(
    "The idiom “on the same page” means:",
    ["in agreement", "sharing a desk", "reading together", "in one meeting"],
    0,
    "It means everyone has a common understanding or agreement.",
    1,
  ),
  q(
    "Choose the closest synonym of CULMINATE.",
    ["begin", "climax", "scatter", "defer"],
    1,
    "To culminate is to reach the highest or final point — the climax.",
    3,
  ),
  q(
    "Complete the phrase: “The leak flew ___ the radar of the hiring committee.”",
    ["under", "over", "behind", "beside"],
    0,
    "Under the radar = unnoticed or unobserved.",
    2,
  ),
  q(
    "One word for “extremely careful and precise”: her code review was ___.",
    ["slovenly", "meticulous", "hasty", "broad"],
    1,
    "Meticulous = showing great attention to detail.",
    2,
  ),
];
